flowchart TD
    t1["`**Test One**`"]
    t1 --"Balanced"--> t2b["`**Test Two**`"]
    t1 --"Imbalanced"--> t2i["`**Test Two**`"]
    t2b --"Balanced"--> t3bb["`**Test Three**`"]
    t3bb --"Balanced"--> solbbb((Solution 1))
    t3bb --"Imbalanced"--> solbbi((Solution 2))
    t2b --"Imbalanced"--> t3bi["`**Test Three**`"]
    t3bi --"Balanced"--> solbib((Solution 3))
    t3bi --"Imbalanced"--> solbii((Solution 4))
    t2i --"Balanced"--> t3ib["`**Test Three**`"] 
    t3ib --"Balanced"--> solibb((Solution 5))
    t3ib --"Imbalanced"--> solibi((Solution 6)) 
    t2i --"Imbalanced"--> t3ii["`**Test Three**`"]
    t3ii --"Balanced"--> soliib((Solution 7))
    t3ii --"Imbalanced"--> soliii((Solution 8))